version: "3"
services:
  web:
    container_name: web-storage-api
    image: alex123189/web-storage-api:1.0
    ports:
      - "1321:1321"
    restart: always
    networks:
      - app
    depends_on:
      - redis
    links:
      - redis:redis
#   We need to set ulimits so that it supports a large amount of requests
#   per second, otherwise the server would be throwing errors on high load.
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - $PWD/data/redis:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - app
networks:
  app:
    driver: bridge