version: "3"
services:
  redis:
    image: "redis:alpine"
    command: database-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/data/database:/var/lib/database
      - $PWD/database.conf:/usr/local/etc/database/database.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4
# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16